import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";
import {
  BUILDER_AI_AGENT_KEY,
  BUILDER_AGENT_KEY,
  BUILDER_BACKEND_AGENT_KEY,
  BUILDER_FRONTEND_AGENT_KEY,
  BUILDER_PLATFORM_AGENT_KEY,
  BUILDER_QA_AGENT_KEY,
  BUILDER_SKILL_KEY,
  INSTANTIATE_BUILD_PLAN_TOOL,
  PAGE_ROUTE,
  PLUGIN_ID,
  PLUGIN_VERSION,
  PROJECT_KEY,
} from "./contract.js";
import { PRODUCT_BUILDER_INSTRUCTIONS, PRODUCT_BUILDER_SKILL_MARKDOWN } from "./agent/product-builder-instructions.js";

const manifest: PaperclipPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: PLUGIN_VERSION,
  displayName: "Product Builder",
  description: "템플릿 기반 제품/서비스 빌드 워크플로우와 Paperclip issue graph를 생성합니다.",
  author: "BBrightCode",
  categories: ["ui", "automation"],
  capabilities: [
    "companies.read",
    "projects.read",
    "projects.managed",
    "agents.read",
    "agents.managed",
    "skills.managed",
    "issues.read",
    "issues.create",
    "issues.update",
    "issue.relations.read",
    "issue.relations.write",
    "plugin.state.read",
    "plugin.state.write",
    "activity.log.write",
    "project.document-slots.read",
    "project.document-slots.write",
    "agent.tools.register",
    "ui.page.register",
    "ui.sidebar.register"
  ],
  entrypoints: {
    worker: "./dist/worker.js",
    ui: "./dist/ui",
  },
  agents: [
    {
      agentKey: BUILDER_AGENT_KEY,
      displayName: "Product Builder",
      role: "delivery-orchestrator",
      title: "Product Builder Orchestrator",
      icon: "layers",
      capabilities: "Instantiates reusable product/service build blueprints and separates reuse decisions from implementation work.",
      adapterType: "claude_local",
      adapterPreference: ["claude_local", "codex_local", "gemini_local"],
      status: "paused",
      budgetMonthlyCents: 0,
      instructions: {
        content: PRODUCT_BUILDER_INSTRUCTIONS,
      },
    },
    {
      agentKey: BUILDER_BACKEND_AGENT_KEY,
      displayName: "Product Builder Backend",
      role: "backend-engineer",
      title: "Product Builder Backend Engineer",
      icon: "server",
      capabilities: "Implements REST/OpenAPI, auth/session, domain data, payment, notification, and backend integration work for Product Builder builds.",
      adapterType: "codex_local",
      adapterPreference: ["codex_local", "claude_local"],
      status: "paused",
      budgetMonthlyCents: 0,
    },
    {
      agentKey: BUILDER_FRONTEND_AGENT_KEY,
      displayName: "Product Builder Frontend",
      role: "frontend-engineer",
      title: "Product Builder Frontend Engineer",
      icon: "layout-template",
      capabilities: "Implements Next.js/Vite UI, public pages, auth modal/action gates, logged-in app flows, and admin screens for Product Builder builds.",
      adapterType: "codex_local",
      adapterPreference: ["codex_local", "claude_local"],
      status: "paused",
      budgetMonthlyCents: 0,
    },
    {
      agentKey: BUILDER_PLATFORM_AGENT_KEY,
      displayName: "Product Builder Platform",
      role: "platform-engineer",
      title: "Product Builder Platform Engineer",
      icon: "cloud",
      capabilities: "Owns delivery repo/workspace binding, Neon, Vercel, environment variables, deployment verification, and operational handoff for Product Builder builds.",
      adapterType: "codex_local",
      adapterPreference: ["codex_local", "claude_local"],
      status: "paused",
      budgetMonthlyCents: 0,
    },
    {
      agentKey: BUILDER_AI_AGENT_KEY,
      displayName: "Product Builder AI Runtime",
      role: "ai-runtime-engineer",
      title: "Product Builder AI Runtime Engineer",
      icon: "sparkles",
      capabilities: "Implements AI server/runtime boundaries, AI job APIs, prompt/runtime contracts, cost guards, and AI observability for web application builds.",
      adapterType: "codex_local",
      adapterPreference: ["codex_local", "claude_local"],
      status: "paused",
      budgetMonthlyCents: 0,
    },
    {
      agentKey: BUILDER_QA_AGENT_KEY,
      displayName: "Product Builder QA",
      role: "qa-engineer",
      title: "Product Builder QA Engineer",
      icon: "badge-check",
      capabilities: "Runs contract, build, browser E2E, public browse/auth modal, deployment smoke, login, and admin-access verification for Product Builder builds.",
      adapterType: "codex_local",
      adapterPreference: ["codex_local", "claude_local"],
      status: "paused",
      budgetMonthlyCents: 0,
    },
  ],
  projects: [
    {
      projectKey: PROJECT_KEY,
      displayName: "Product Builder",
      description: "Product Builder가 생성한 제품/서비스 빌드 issue와 재사용 판정 기록을 모으는 프로젝트.",
      status: "in_progress",
      color: "#0f766e",
    },
  ],
  skills: [
    {
      skillKey: BUILDER_SKILL_KEY,
      displayName: "Product Builder",
      slug: "product-builder",
      description: "Reusable product/service build workflow instantiation with explicit REUSE/EXTEND/NEW/N/A decisions.",
      markdown: PRODUCT_BUILDER_SKILL_MARKDOWN,
    },
  ],
  tools: [INSTANTIATE_BUILD_PLAN_TOOL],
  ui: {
    slots: [
      {
        type: "page",
        id: "product-builder-page",
        displayName: "Product Builder",
        exportName: "ProductBuilderPage",
        routePath: PAGE_ROUTE,
        order: 35,
      },
      {
        type: "sidebar",
        id: "product-builder-sidebar",
        displayName: "Product Builder",
        exportName: "ProductBuilderSidebarItem",
        order: 35,
      },
    ],
  },
};

export default manifest;
